spring:
  application:
    name: AuthenticationService-ms

  datasource:
    url: jdbc:mysql://localhost:3306/harikumar
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 2222